version: "2"
plugins:
  duplication:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
exclude_patterns:
  - "versioneer.py"
  - "src/gardena/_version.py"
  - "tests/gardena_api_return"
  - "tests/"