language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install codecov wheel cmarkgfm
- pip install --upgrade pytest
script:
- python setup.py test
after_script:
- bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r reports/coverage.xml -l Python
- codecov
deploy:
  provider: pypi
  user: smart-gardena-token
  password:
    secure: KtUScw95g5y80bdJ8foEsfOzc+aTd+qGFoDOdeWLf4qQZHdhlsYerjc/LAu08Ck+Oz2Aa39+EGI91j0FcTltkT3swkrLkJxkdWICGHG4JMCjMsS6B9NpqcB8KkCoxuSoHdYeKpeJeze6p3fO0TtvjJ5UYC077qmFHdEPk952JsSRHcfZJ4Kg/q1uEma3rS1xozGoVpjTcXvT4Ttw/Uv2wGDwoJElaO3w8bmZgKKQ0AiywZGq8C6h8MHBk5RzrqFzIqc1hBhOkD4JfHftOOqfCWslFr17cixmY9OnAj/W2AEpvHafs4WDeejPnpIqN6C+F4kw7hZjNPTaHJUBIKhHECFp8DqoW2YU+9xb/eK06bW3uh7UpFdRfuiWISdEK1H+Ze/Nni+iHnw5NRkajcK9ESTZCJkaDhYHKTYXwYtm5UMft1Eztg+bVuqVqq5hSc6vhuAL6VTiNJjAk6WzAborbeiOuh+c7t8foxJUFaF9//RTd0OhaSaxFZvCIl7uQVY0EbKhG7Y4XYbDwoSqI3N2NymjbrgAexXhPd0DNx7OAAZ9RkZklHr7Jx2R6GMDLgbUsiy9D2OMc0ehe4ZfUUqw5u99kuWpSkncZmfnTjDmS7HN2uVo93q14IAtYzufiTN4Ai73LFd4djzRSdtVlpN5Agboz9Er5hgMJX+bXlBIVlI=
  on:
    tags: true
    branch: master
    python: '3.7'
  distributions: register sdist bdist_wheel
