[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.pytest_cache
  | \.tox
  | \.venv
  | \.eggs
  | \.coverage
  | _build
  | buck-out
  | build
  | dist
)/
'''